######################## vars ########################
variables:
  PROJECT_NAME: "product-add"

######################## stages ########################
stages:
- sast_check
- SCA-Check
- secret_check
- build

######################## build ########################
.build-docker:
  stage: build
  image: ${DOCKER_REGISTRY_MIRROR}/basalam/docker:20.10.7-custom
  script:
  - docker login ${DOCKER_REGISTRY_MIRROR} -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS}
  - DOCKER_BUILDKIT=1 docker buildx build . --push --cache-from=type=registry,ref=${IMAGE_NAME}:build-cache
    --cache-to=type=registry,ref=${IMAGE_NAME}:build-cache,mode=max -t ${IMAGE_NAME}:${IMAGE_TAG}
    --output=type=image,push=true --builder builder-1
  tags:
  - buildx

######################## staging ########################
build docker image dev:
  extends: .build-docker
  except:
  - master
  - tags
  when: manual
  variables:
    IMAGE_NAME: ${DOCKER_REGISTRY_MIRROR}/basalam/${PROJECT_NAME}/dev
    IMAGE_TAG: ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}

######################## production ########################
build docker image master:
  extends: .build-docker
  only:
  - tags
  variables:
    IMAGE_NAME: ${DOCKER_REGISTRY_MIRROR}/basalam/${PROJECT_NAME}/master
    IMAGE_TAG: ${CI_COMMIT_TAG}
  before_script:
  - bash -c "if [[ ${CI_COMMIT_TAG} =~ ${SEMVER_REGEX} ]]; then exit 0; else exit
    1; fi"

include:
- remote: https://git.basalam.dev/devops-public/security/-/raw/master/gitlab-ci/SAST.gitlab-ci.yml
- remote: https://git.basalam.dev/devops/security/-/raw/master/gitlab-ci/Dependency-Scanning.gitlab-ci.yml
- remote: https://git.basalam.dev/devops-public/security/-/raw/master/gitlab-ci/Secret-Detection.gitlab-ci.yml
